sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAgT6yHDr1Xdz83MFbh
    access-key-secret: 1Z7Lsxi3xrLMk3bMV8KKpHYN6Zi0tz
    bucket-name: sky-take-out-rx